name: RunSync Tasks

on:
  workflow_dispatch:
    inputs:
      task_type:
        description: "Task to run"
        required: true
        default: "update_activities"
        type: choice
        options:
          - update_activities
          - update_p4_p7
          - transfer_garmin_stop
          - transfer_garmin_no_stop
      password:
        description: "Password for authentication"
        required: true
        type: string

jobs:
  runsync-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip curl locales xvfb
          sudo locale-gen de_DE.UTF-8

      - name: Install Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          # Get Chrome version for debugging
          google-chrome --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify password
        run: |
          if [ "${{ github.event.inputs.password }}" != "${{ secrets.ADMIN_PASSWORD }}" ]; then
            echo "❌ Invalid password"
            exit 1
          fi
          echo "✅ Password verified"

      - name: Run Update Activities Task
        if: github.event.inputs.task_type == 'update_activities'
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          DOCUMENT_NAME: ${{ secrets.DOCUMENT_NAME }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          echo "🚀 Starting Update Activities Task..."
          python -c "
          from main_app import update_activities_since_first_not_completed_day
          from strava_client import StravaClient
          from sheets_client import SheetsClient

          strava_client = StravaClient()
          sheets_client = SheetsClient()

          try:
              update_activities_since_first_not_completed_day(sheets_client, strava_client)
              print('✅ Update Activities Task completed successfully!')
          except Exception as e:
              print(f'❌ Update Activities Task failed: {e}')
              exit(1)
          "

      - name: Run Update P4/P7 Worksheets Task
        if: github.event.inputs.task_type == 'update_p4_p7'
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          DOCUMENT_NAME: ${{ secrets.DOCUMENT_NAME }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          echo "🚀 Starting Update P4/P7 Worksheets Task..."
          python -c "
          from main_app import update_p4_p7_worksheets
          from strava_client import StravaClient
          from sheets_client import SheetsClient

          strava_client = StravaClient()
          sheets_client = SheetsClient()

          try:
              update_p4_p7_worksheets(sheets_client, strava_client)
              print('✅ Update P4/P7 Worksheets Task completed successfully!')
          except Exception as e:
              print(f'❌ Update P4/P7 Worksheets Task failed: {e}')
              exit(1)
          "

      - name: Run Garmin Transfer with Stop Task
        if: github.event.inputs.task_type == 'transfer_garmin_stop'
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          DOCUMENT_NAME: ${{ secrets.DOCUMENT_NAME }}
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          # Start virtual display for non-headless Chrome
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 2
          echo "🚀 Starting Garmin Transfer with Stop Task..."
          python -c "
          from main_app import transfer_activities_from_Strava_to_Garmin_until_already_transferred
          from strava_client import StravaClient
          from garmin_client import GarminClient
          from selenium.webdriver.support.ui import WebDriverWait
          import undetected_chromedriver as uc

          strava_client = StravaClient()
          garmin_client = GarminClient()

          # Chrome options will be created fresh for each attempt

          # Use undetected_chromedriver with manual ChromeDriver management
          import os
          import subprocess

          # Get Chrome version
          chrome_version = subprocess.check_output(['google-chrome', '--version']).decode('utf-8').strip()
          print('Chrome version:', chrome_version)

          # Extract major version number
          major_version = chrome_version.split()[2].split('.')[0]
          print('Chrome major version:', major_version)

          driver = None
          try:
              # Create fresh options for each attempt
              options1 = uc.ChromeOptions()
              # Remove --headless for Garmin compatibility
              options1.add_argument('--no-sandbox')
              options1.add_argument('--disable-dev-shm-usage')
              options1.add_argument('--disable-gpu')
              options1.add_argument('--window-size=1920,1080')
              options1.add_argument('--disable-extensions')
              options1.add_argument('--disable-plugins')
              options1.add_argument('--disable-images')
              options1.add_argument('--disable-javascript')
              
              # Try with the detected major version
              print('Attempting to start ChromeDriver with version', major_version)
              driver = uc.Chrome(options=options1, version_main=int(major_version))
              print('ChromeDriver started successfully with version', major_version)
          except Exception as e:
              print('Failed with version', major_version, ':', str(e))
              try:
                  # Create fresh options for second attempt
                  options2 = uc.ChromeOptions()
                  # Remove --headless for Garmin compatibility
                  options2.add_argument('--no-sandbox')
                  options2.add_argument('--disable-dev-shm-usage')
                  options2.add_argument('--disable-gpu')
                  options2.add_argument('--window-size=1920,1080')
                  options2.add_argument('--disable-extensions')
                  options2.add_argument('--disable-plugins')
                  options2.add_argument('--disable-images')
                  options2.add_argument('--disable-javascript')
                  
                  # Try with auto-detection as fallback
                  print('Attempting to start ChromeDriver with auto-detection')
                  driver = uc.Chrome(options=options2, version_main=None)
                  print('ChromeDriver started successfully with auto-detection')
              except Exception as e2:
                  print('Auto-detection also failed:', str(e2))
                  try:
                      # Create fresh options for third attempt
                      options3 = uc.ChromeOptions()
                      # Remove --headless for Garmin compatibility
                      options3.add_argument('--no-sandbox')
                      options3.add_argument('--disable-dev-shm-usage')
                      options3.add_argument('--disable-gpu')
                      options3.add_argument('--window-size=1920,1080')
                      options3.add_argument('--disable-extensions')
                      options3.add_argument('--disable-plugins')
                      options3.add_argument('--disable-images')
                      options3.add_argument('--disable-javascript')
                      
                      # Try with a slightly older version
                      print('Attempting to start ChromeDriver with version', int(major_version) - 1)
                      driver = uc.Chrome(options=options3, version_main=int(major_version) - 1)
                      print('ChromeDriver started successfully with version', int(major_version) - 1)
                  except Exception as e3:
                      print('All attempts failed:', str(e3))
                      raise
          wait = WebDriverWait(driver, 20)

          try:
              transfer_activities_from_Strava_to_Garmin_until_already_transferred(strava_client, garmin_client, driver, wait)
              print('✅ Garmin Transfer with Stop Task completed successfully!')
          except Exception as e:
              print(f'❌ Garmin Transfer with Stop Task failed: {e}')
              exit(1)
          finally:
              driver.quit()
          "

      - name: Run Garmin Transfer without Stop Task
        if: github.event.inputs.task_type == 'transfer_garmin_no_stop'
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          DOCUMENT_NAME: ${{ secrets.DOCUMENT_NAME }}
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          # Start virtual display for non-headless Chrome
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 2
          echo "🚀 Starting Garmin Transfer without Stop Task..."
          python -c "
          from main_app import transfer_all_activities_not_yet_transferred_from_Strava_to_Garmin_without_stop
          from strava_client import StravaClient
          from garmin_client import GarminClient
          from selenium.webdriver.support.ui import WebDriverWait
          import undetected_chromedriver as uc

          strava_client = StravaClient()
          garmin_client = GarminClient()

          # Chrome options will be created fresh for each attempt

          # Use undetected_chromedriver with manual ChromeDriver management
          import os
          import subprocess

          # Get Chrome version
          chrome_version = subprocess.check_output(['google-chrome', '--version']).decode('utf-8').strip()
          print('Chrome version:', chrome_version)

          # Extract major version number
          major_version = chrome_version.split()[2].split('.')[0]
          print('Chrome major version:', major_version)

          driver = None
          try:
              # Create fresh options for each attempt
              options1 = uc.ChromeOptions()
              # Remove --headless for Garmin compatibility
              options1.add_argument('--no-sandbox')
              options1.add_argument('--disable-dev-shm-usage')
              options1.add_argument('--disable-gpu')
              options1.add_argument('--window-size=1920,1080')
              options1.add_argument('--disable-extensions')
              options1.add_argument('--disable-plugins')
              options1.add_argument('--disable-images')
              options1.add_argument('--disable-javascript')
              
              # Try with the detected major version
              print('Attempting to start ChromeDriver with version', major_version)
              driver = uc.Chrome(options=options1, version_main=int(major_version))
              print('ChromeDriver started successfully with version', major_version)
          except Exception as e:
              print('Failed with version', major_version, ':', str(e))
              try:
                  # Create fresh options for second attempt
                  options2 = uc.ChromeOptions()
                  # Remove --headless for Garmin compatibility
                  options2.add_argument('--no-sandbox')
                  options2.add_argument('--disable-dev-shm-usage')
                  options2.add_argument('--disable-gpu')
                  options2.add_argument('--window-size=1920,1080')
                  options2.add_argument('--disable-extensions')
                  options2.add_argument('--disable-plugins')
                  options2.add_argument('--disable-images')
                  options2.add_argument('--disable-javascript')
                  
                  # Try with auto-detection as fallback
                  print('Attempting to start ChromeDriver with auto-detection')
                  driver = uc.Chrome(options=options2, version_main=None)
                  print('ChromeDriver started successfully with auto-detection')
              except Exception as e2:
                  print('Auto-detection also failed:', str(e2))
                  try:
                      # Create fresh options for third attempt
                      options3 = uc.ChromeOptions()
                      # Remove --headless for Garmin compatibility
                      options3.add_argument('--no-sandbox')
                      options3.add_argument('--disable-dev-shm-usage')
                      options3.add_argument('--disable-gpu')
                      options3.add_argument('--window-size=1920,1080')
                      options3.add_argument('--disable-extensions')
                      options3.add_argument('--disable-plugins')
                      options3.add_argument('--disable-images')
                      options3.add_argument('--disable-javascript')
                      
                      # Try with a slightly older version
                      print('Attempting to start ChromeDriver with version', int(major_version) - 1)
                      driver = uc.Chrome(options=options3, version_main=int(major_version) - 1)
                      print('ChromeDriver started successfully with version', int(major_version) - 1)
                  except Exception as e3:
                      print('All attempts failed:', str(e3))
                      raise
          wait = WebDriverWait(driver, 20)

          try:
              print('Starting Garmin transfer process...')
              transfer_all_activities_not_yet_transferred_from_Strava_to_Garmin_without_stop(strava_client, garmin_client, driver, wait)
              print('✅ Garmin Transfer without Stop Task completed successfully!')
          except Exception as e:
              print('❌ Garmin Transfer without Stop Task failed:')
              print('Error type:', type(e).__name__)
              print('Error message:', str(e))
              import traceback
              print('Full traceback:')
              traceback.print_exc()
              exit(1)
          finally:
              if driver:
                  driver.quit()
          "

      - name: Task completed
        run: |
          echo "🎉 Task '${{ github.event.inputs.task_type }}' completed successfully!"
          echo "📊 Check the logs above for detailed information."
